# Generated by Django 2.2.4 on 2019-08-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5)),
                ('email', models.CharField(default='', max_length=50)),
                ('birthday', models.DateField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
